/**
 * Comprehensive dictionary of English collocations, phrasal verbs, idioms,
 * compound nouns, prepositional phrases, and multi-word expressions for intelligent
 * single-click phrase recognition in English texts.
 */

export const EXTENDED_ENGLISH_PHRASES: string[] = [
  // 1. Geography, Landmarks, Culture & History
  'great wall of china', 'great wall', 'forbidden city', 'palace museum', 'imperial palace',
  'summer palace', 'temple of heaven', 'tiananmen square', 'ming dynasty', 'qing dynasty',
  'han dynasty', 'tang dynasty', 'song dynasty', 'terracotta army', 'terracotta warriors',
  'silk road', 'yellow river', 'yangtze river', 'pearl river', 'west lake', 'mount tai',
  'mount huang', 'mount everest', 'himalayan mountains', 'united states', 'united kingdom',
  'new york city', 'san francisco', 'los angeles', 'pacific ocean', 'atlantic ocean',
  'middle east', 'southeast asia', 'east asia', 'european union', 'latin america',

  // 2. Nature, Landscapes & Descriptive Collocations
  'rolling green mountains', 'rolling green hills', 'rolling hills', 'mountain range',
  'green mountains', 'green hills', 'snow-capped mountains', 'dense forest', 'tropical rainforest',
  'vast grasslands', 'calm waters', 'rushing river', 'sandy beach', 'coastal region',
  'natural habitat', 'wildlife sanctuary', 'breathtaking scenery', 'spectacular views',
  'spectacular view', 'panoramic view', 'picturesque landscape', 'dramatic scenery',
  'colossal stone structure', 'stone structure', 'massive stone structure', 'ancient architecture',
  'historical landmark', 'cultural heritage', 'world heritage site', 'archaeological site',
  'profound sense of awe', 'sense of awe', 'sense of wonder', 'sense of pride',
  'sense of belonging', 'sense of responsibility', 'sense of urgency', 'sense of humor',
  'sense of direction', 'sense of purpose', 'peace of mind', 'state of mind',
  'quality of life', 'cost of living', 'standard of living', 'way of life',
  'winding gracefully', 'wind gracefully', 'standing atop', 'stand atop',
  'step into', 'stepping into', 'step back into', 'stepping back into',
  'walk through', 'walking through', 'hundreds of years', 'thousands of years',
  'five hundred years', 'daily life', 'everyday life', 'modern society',
  'traditional customs', 'cultural diversity', 'social harmony',

  // 3. Phrasal Verbs (Essential & Advanced)
  'take care of', 'look forward to', 'give up', 'run out of', 'pay attention to',
  'come across', 'get rid of', 'set up', 'figure out', 'find out', 'look up to',
  'carry out', 'bring about', 'point out', 'turn down', 'break down', 'cut down on',
  'put off', 'call off', 'hold on', 'deal with', 'rely on', 'depend on', 'focus on',
  'consist of', 'participate in', 'result in', 'lead to', 'belong to', 'apply for',
  'suffer from', 'care about', 'believe in', 'agree with', 'listen to', 'laugh at',
  'think about', 'worry about', 'look at', 'look for', 'look after', 'take part in',
  'make sense of', 'catch up with', 'keep up with', 'get along with', 'put up with',
  'look down on', 'come up with', 'face up to', 'run into', 'stand up for', 'fall back on',
  'back out of', 'go through with', 'cut back on', 'drop out of', 'fit in with',
  'get away with', 'live up to', 'make up for', 'look in on', 'check up on',
  'brush up on', 'do away with', 'read up on', 'sign up for', 'stand in for',
  'talk down to', 'watch out for', 'zero in on', 'zoom in on', 'warm up to',
  'wind up with', 'work out for', 'turn out to be', 'stand out from', 'blend in with',
  'cater to', 'cope with', 'strive for', 'yearn for', 'embark on', 'delve into',
  'tap into', 'stem from', 'boil down to', 'account for', 'allow for', 'appeal to',
  'avail oneself of', 'back up', 'bear with', 'blow away', 'bounce back from',
  'break out of', 'bring forward', 'bring up', 'build upon', 'burst into',
  'butt in', 'call upon', 'calm down', 'carry over', 'catch on', 'charge with',
  'clear up', 'close in on', 'come down to', 'come into contact with', 'come to terms with',
  'comply with', 'concentrate on', 'conform to', 'contribute to', 'count on',
  'dawn on', 'decide upon', 'depart from', 'derive from', 'deviate from',
  'die down', 'dispose of', 'draw back from', 'draw upon', 'drive at',
  'dwell upon', 'ease into', 'end up with', 'engage in', 'entail in',
  'equate with', 'exert upon', 'explain away', 'face up to', 'fall apart',
  'fall behind with', 'fall short of', 'feed into', 'fend off', 'fill in for',
  'flesh out', 'focus upon', 'forge ahead with', 'gain on', 'gear towards',
  'get ahead of', 'get around to', 'get by on', 'get down to', 'get over with',
  'give way to', 'glance over', 'go along with', 'go hand in hand with', 'grapple with',
  'gravitate towards', 'guard against', 'hand down to', 'hang onto', 'hark back to',
  'head towards', 'hinge on', 'hold back from', 'hold out for', 'hunt down',
  'impact on', 'impose upon', 'improve on', 'indulge in', 'inquire into',
  'insist on', 'interact with', 'interfere with', 'invest in', 'iterate on',
  'keep pace with', 'kick off with', 'knock down', 'lapse into', 'launch into',
  'lay off', 'lead up to', 'lean towards', 'level off', 'line up with',
  'linger on', 'live on', 'lock into', 'log into', 'look back on',
  'make away with', 'make out', 'make headway in', 'mark out', 'match up with',
  'measure up to', 'meddle in', 'merge into', 'narrow down to', 'negotiate with',
  'opt for', 'originate from', 'pan out', 'part with', 'pass away',
  'pass off as', 'patch up', 'pay off', 'persist in', 'pertain to',
  'phase out', 'pile up', 'pin down', 'pitch in', 'play down',
  'play into', 'plug into', 'plunge into', 'point towards', 'prevail over',
  'pride oneself on', 'proceed with', 'provide for', 'pull off', 'pull through',
  'push ahead with', 'push forward with', 'qualify for', 'quarrel with', 'radiate from',
  'rail against', 'reach out to', 'read into', 'rebound from', 'reckon on',
  'reconcile with', 'recover from', 'refer to', 'reflect on', 'refrain from',
  'relate to', 'remain in', 'remedy for', 'reminisce about', 'remind of',
  'render into', 'renounce to', 'resort to', 'respond to', 'rest upon',
  'result from', 'retain for', 'revolve around', 'reward with', 'root for',
  'round off with', 'rule out', 'run abreast of', 'run across', 'run down',
  'rustle up', 'scale back on', 'scale up', 'scout out', 'screen out',
  'see through', 'seek after', 'serve as', 'set aside for', 'set forth',
  'set in motion', 'settle down to', 'settle for', 'shake off', 'shift towards',
  'shrug off', 'shut down', 'side with', 'single out', 'sift through',
  'sink in', 'sit in on', 'skim through', 'slack off', 'slip up',
  'slow down', 'smooth out', 'snap up', 'sort out', 'spark off',
  'speak up for', 'specialize in', 'speed up', 'spell out', 'spill over into',
  'spin off', 'split up with', 'spread out', 'spring from', 'spruce up',
  'spur on', 'square with', 'squeeze out of', 'stake out', 'stamp out',
  'stand by', 'stand for', 'stave off', 'stay abreast of', 'steer clear of',
  'stem the tide of', 'step down from', 'step up to', 'stick to', 'stick up for',
  'stock up on', 'stoop to', 'strike out', 'strike up', 'stumble upon',
  'submit to', 'subscribe to', 'subside into', 'succeed in', 'succumb to',
  'suit up for', 'sum up', 'summon up', 'surrender to', 'swear by',
  'sweep away', 'switch over to', 'sympathize with', 'sync up with', 'tackle with',
  'tail off', 'take after', 'take aback by', 'take apart', 'take back',
  'take for granted', 'take in stride', 'take into account', 'take into consideration',
  'take off', 'take on', 'take out on', 'take over from', 'take pride in',
  'take refuge in', 'take root in', 'take the place of', 'take to heart',
  'tangle with', 'tear down', 'tell apart', 'test out', 'thaw out',
  'thrive on', 'throw light on', 'tidy up', 'tie in with', 'tighten up on',
  'tip off', 'tire of', 'toll for', 'tone down', 'top off with',
  'touch on', 'touch upon', 'toy with', 'track down', 'trade off with',
  'transform into', 'transition to', 'tread on', 'trigger off', 'trim down',
  'trip over', 'trust in', 'try out', 'turn against', 'turn away from',
  'turn around', 'turn into', 'turn over to', 'uncover for', 'underpin with',
  'unfold before', 'unravel for', 'upgrade to', 'urge on', 'usher in',
  'venture into', 'vie for', 'voice support for', 'vote down', 'vouch for',
  'wade through', 'wait up for', 'wake up to', 'walk away from', 'walk out on',
  'ward off', 'wash away', 'waste away', 'watch over', 'water down',
  'wave aside', 'wean off', 'wear down', 'wear off', 'weave into',
  'weigh in on', 'weigh up', 'whip up', 'whittle down', 'win over',
  'wipe out', 'wire up to', 'withdraw from', 'work around', 'wrestle with',
  'write off', 'yield to',

  // 4. Prepositional, Transitional & Logical Connectors
  'as well as', 'in front of', 'according to', 'in order to', 'because of',
  'due to', 'thanks to', 'instead of', 'in terms of', 'in addition to',
  'on behalf of', 'with respect to', 'in spite of', 'regardless of',
  'as long as', 'as soon as', 'by the way', 'for example', 'for instance',
  'in fact', 'at least', 'on the other hand', 'on one hand', 'first of all',
  'above all', 'after all', 'in the meantime', 'at the same time', 'not far from',
  'as a result', 'as a consequence', 'in consequence of', 'in light of',
  'in view of', 'with regard to', 'in comparison with', 'in contrast to',
  'on the contrary', 'by contrast', 'in other words', 'to put it simply',
  'to sum up', 'in conclusion', 'in summary', 'all in all', 'by and large',
  'for the most part', 'in general', 'on the whole', 'generally speaking',
  'strictly speaking', 'roughly speaking', 'broadly speaking', 'to begin with',
  'last but not least', 'needless to say', 'it goes without saying that',
  'under no circumstances', 'in no case', 'on no account', 'by all means',
  'by no means', 'to some extent', 'to a certain degree', 'more or less',
  'sooner or later', 'now and then', 'from time to time', 'once in a while',
  'every now and then', 'day in and day out', 'little by little', 'step by step',
  'hand in hand', 'side by side', 'face to face', 'back to back',
  'shoulder to shoulder', 'arm in arm', 'head over heels', 'word for word',
  'heart to heart', 'eye to eye', 'upside down', 'inside out',

  // 5. Idiomatic Expressions & Common Sayings
  'blessing in disguise', 'piece of cake', 'break a leg', 'bite the bullet',
  'burn the midnight oil', 'call it a day', 'cost an arm and a leg',
  'cut corners', 'hit the nail on the head', 'kill two birds with one stone',
  'let the cat out of the bag', 'miss the boat', 'once in a blue moon',
  'spill the beans', 'take with a grain of salt', 'taste of your own medicine',
  'under the weather', 'water under the bridge', 'actions speak louder than words',
  'add insult to injury', 'barking up the wrong tree', 'beat around the bush',
  'better late than never', 'cross that bridge when you come to it',
  'devil is in the details', 'every cloud has a silver lining',
  'get out of hand', 'good things come to those who wait',
  'haste makes waste', 'hit the sack', 'in the heat of the moment',
  'keep an eye on', 'leave no stone unturned', 'make matters worse',
  'no pain no gain', 'on the fence', 'play devil advocate',
  'pull someone leg', 'see eye to eye', 'speak of the devil',
  'the ball is in your court', 'the best of both worlds', 'the last straw',
  'through thick and thin', 'time flies when having fun', 'to each his own',
  'wrap your head around', 'you can say that again',

  // 6. Technology, Science, Computing & Business Collocations
  'artificial intelligence', 'machine learning', 'deep learning', 'neural network',
  'neural networks', 'computer vision', 'natural language processing', 'large language model',
  'large language models', 'autonomous driving', 'self driving', 'autonomous vehicle',
  'cloud computing', 'data science', 'big data', 'cyber security',
  'operating system', 'source code', 'user interface', 'user experience',
  'real time', 'in real time', 'cross-language', 'cross platform',
  'voice assistant', 'smart home', 'mobile application', 'web application',
  'database management', 'version control', 'continuous integration',
  'virtual reality', 'augmented reality', 'quantum computing', 'speech recognition',
  'reinforcement learning', 'generative ai', 'foundation model', 'distributed system',
  'high performance', 'edge computing', 'digital transformation', 'supply chain',
  'business model', 'target audience', 'market share', 'competitive advantage',
  'return on investment', 'customer satisfaction', 'human resources',
  'decision making', 'problem solving', 'critical thinking', 'team building',
  'project management', 'strategic planning', 'sustainable development',
  'renewable energy', 'climate change', 'carbon footprint', 'greenhouse gas',
  'global warming', 'solar power', 'wind energy', 'circular economy',

  // 7. Academic, Scholarly & Educational Phrases
  'language learning', 'second language', 'target language', 'native speaker',
  'flash card', 'flash cards', 'spaced repetition', 'active recall',
  'reading comprehension', 'listening comprehension', 'written expression',
  'oral communication', 'critical analysis', 'peer review', 'case study',
  'empirical evidence', 'qualitative research', 'quantitative research',
  'field of view', 'human race', 'human beings', 'socioeconomic status',
  'historical context', 'philosophical inquiry', 'cognitive development',
  'neural plasticity', 'working memory', 'long-term memory', 'short-term memory'
];
